print("Hello World")
print("Hello","World")
print("Mi nombre es ", end='')
print('Luis Pinto') 
print('Mi','nombre','es','Luis','Pinto',sep='.')
print("Mi", "nombre", "es", sep="_", end="*")
print("Luis", "Pinto.", sep="*", end="*\n")
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****\n"*2)
print("    **\n   *  *\n  *    *\n *      *\n***    ***\n  *    *\n  *    *\n  ******\n"*2)